version: '2'
services:
  data:
    image: busybox
    container_name: busybox
    volumes:
      - ~/www:/var/www/html
      - ~/data:/var/lib/mysql
    networks:
     - red

  apache:
    image: andresvega565/centos-httpd-php
    container_name: httpd
    ports:
      - "8080:80"
      - "2223:22"
    volumes_from:
      - data
    networks:
     - red

  mysql:
    image: orboan/dcsss-mariadb
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER1: www
      MYSQL_ROOT_PASSWORD: iaw
    ports:
      - "3307:3307"
    volumes_from:
     - data
    networks:
     - red

networks:
  red:
    driver: bridge
    ipam:
      config:
       - subnet: 192.168.1.0/24
